version: '3'



services:
  prometheus:
    container_name: prom_server
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'



volumes:
  prom_data: {}